# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PlayerDataSQL自动构建

on:
  push:
    branches: [ "mc-1.12.2" ]
  pull_request:
    branches: [ "mc-1.12.2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: |
        bash setup.sh
        mvn -B package --file pom.xml

    - name: Extract GAV
      id: extract
      uses: andreacomo/maven-gav-extractor@v2

    - name: Log GAV
      run: |
        echo ${{ steps.extract.outputs.group-id }}
        echo ${{ steps.extract.outputs.artifact-id }}
        echo ${{ steps.extract.outputs.version }}
        echo ${{ steps.extract.outputs.name }}
      shell: bash

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update artifacts
      uses: actions/upload-artifact@v4
      with:
        path: target/*.jar
        name: PlayerDataSQL

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: V${{ steps.extract.outputs.version }}
        files: target/${{ steps.extract.outputs.name }}_${{ steps.extract.outputs.version }}.jar

